# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 5423662eebc1b622eb19f38d0014f48944f4fc69

{
  "title": "Шкаф IKEA55",
  "description": "Срочн55"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/187/
Content-Type: application/json
Authorization: Token 5423662eebc1b622eb19f38d0014f48944f4fc69

{
  "status": "CLOSED"
}

###

# удалить обьявление
DELETE {{baseUrl}}/advertisements/74/
Content-Type: application/json
Authorization: Token 5423662eebc1b622eb19f38d0014f48944f4fc69

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=2
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2020-10-01
Content-Type: application/json
